### ISSUE TITLE
getting value of array elements

### ISSUE THREAD

**Issue by slopokeit** [panates/hl7v2#1]
Thanks for contributing the project!  I've been trying it out to see if it can fit our need. 

How does one get access to the items in the `this._data` array?  `HL7Field.value()` only returns the first element.  IE in my example below.. how do I get the patient's first and last name from the PID segment?

Do you have any plans mapping the `HL7Segment` to a JSON object?

```
const pid = message.getSegment('PID', 0);
console.log(pid.PatientId.value, pid.PatientName.toHL7(), pid.PatientName.value);
console.log(pid);
```

![image](https://user-images.githubusercontent.com/22594095/55094703-4208e200-508d-11e9-959c-dbd910aa7bd7.png)

**Comment by erayhanoglu** [comment]
Hello. Thank you for interested in library.

Accessing repetitions and elements is very simple. Here is an example code shows how.

```js
const msg = HL7Message.parse('MSH|^~\\&|1A^1B^1C^1D~2A^2B^2C^2D');
// This is a short link of first repetitions first element 
console.log(msg.MSH.SendingApplication.value);
// This is a short link of repetition at 0 index's first element 
console.log(msg.MSH.SendingApplication[0].value);
// Returns value from repetition index 0 element number 1
console.log(msg.MSH.SendingApplication[0][1].value);
console.log(msg.MSH.SendingApplication[0][2].value);
console.log(msg.MSH.SendingApplication[0][3].value);
console.log(msg.MSH.SendingApplication[0][4].value);

console.log(msg.MSH.SendingApplication[1].value);
console.log(msg.MSH.SendingApplication[1][1].value);
console.log(msg.MSH.SendingApplication[1][2].value);
console.log(msg.MSH.SendingApplication[1][3].value);
console.log(msg.MSH.SendingApplication[1][4].value);
```
