### ISSUE TITLE
\n replace in test message

### ISSUE THREAD

**Issue by bluepuma77** [panates/hl7v2#11]
To me it looks like the test message in `test/09_server.js` is only replacing a single occurrence of \n:

```
const sampleMessage1 = `MSH|^~\\&|LCS|LCA|LIS|TEST9999|19980731153200||ORU^R01|1234|P|2.2
...
NTE|1|L|ROUTINE RESPIRATORY FLORA
`.replace(/\n/, '\r');
```

Shouldn't it be `.replace(/\n/g, '\r');`

**Comment by erayhanoglu** [comment]
Yes you are right. Just updated and committed.
