### ISSUE TITLE
How to process all ADT messages?

### ISSUE THREAD

**Issue by bluepuma77** [panates/hl7v2#12]
The examples only "listen" to a single message type, like `server.use(('ORU^R01', oru) => {`.

Is it possible to set up a handler for all messages or a group of messages like 'ADT'?

**Comment by bluepuma77** [comment]
The example above was from your [comment](https://github.com/panates/hl7v2/issues/10#issuecomment-665689207), in test it looks like 
`server.use('ORU^R01', (req) => {` 
or 
`server.use((req) => {`

**Comment by erayhanoglu** [comment]
Ofcourse you can. You can listen for all messages like this.
```js
server.use((msg) => {
});
```
