### ISSUE TITLE
"Encoding not recognized" error message

### ISSUE THREAD

**Issue by bluepuma77** [panates/hl7v2#13]
During testing with various messages I sometimes get an error message:

```ERR|^^^&Encoding not recognized: '' (searched as: '')```

This is not a string I can find in the source, and I saw that encoding should default to utf-8.

Do you know where this is coming from?

**Comment by bluepuma77** [comment]
Example message which throws the error
```
// msg.js
const msg2 = `MSH|^~\&|XXX|ORBIS|YYY|ZZZ|202007080829||ADT^A01|22222222|P|2.3|||||D||DE
EVN|
PID|
PV1|1|I|3A BAX^325^B1^GB_BAX^MHV^999999||||||||||||||||5555555
`.replace(/\n/g, '\r');

process.stdout.write(msg);
```

I pipe the output to a file and then use this to send it to the server:

```
node msg.js > A01.hl7
echo -n -e "\x0b$(cat A01.hl7)\x1c\x0d" | nc localhost 7777
```

**Comment by erayhanoglu** [comment]
The error is thrown by "iconv-lite" module. Look at HL7Message.js line 123.

**Comment by bluepuma77** [comment]
Thanks
