### ISSUE TITLE
Null value handling

### ISSUE THREAD

**Issue by elysion** [panates/hl7v2#14]
According to the HL7Wiki, a null value should be denoted with two double quotes (https://wiki.hl7.org/Null). If you use such a value for a date field and try to parse the message with HL7Message.parse, you get the following error:

`Error: Invalid date string """"`

The used message:
`MSH|^~\&|Sectra|Sectra RIS|System|Facility|20200909105818.540+0200||SIU^S12|489A4F8E71ED44038E9343F8558A7B8F|P|2.4
SCH||||||NW^Booking appointed|||||^^20^20200910105800|||||||||||||||RAVIL00000000829|RAVIL00000000829
PID|||20200909104829902||Balba^Allan^^^""||20200901|M|||Fjugeholm^^Skumla^^69304|""|||||||||||||||||""
PV1|||""
RGS|1
AIS|1||82400|20200910105800|||20.000000|M
AIG|1||^^^VillageCR|ROOM^Examination room`

I browsed through the code to find a place to update the behaviour, but was unsure where would be the correct place to make them. Have you discussed this? Do you have ideas on how the null values should be handled?

**Comment by erayhanoglu** [comment]
Thank you for your feedback. Null values has been implemented.
