### ISSUE TITLE
Custom (Z) segment support

### ISSUE THREAD

**Issue by elysion** [panates/hl7v2#15]
It seems the library does not currently support custom HL7 segments i.e. the so called Z-segments. When a message with a Z-segment is passed to HL7Message.parse an error is thrown (such as `ParseError: Unknown HL7 segment type (ZDS)`).

Do you have plans of building support for custom segments or thoughts on how the support should be implemented?

**Comment by erayhanoglu** [comment]
Hi. I'am sorry it does not support custom segments for now. We plan to work on a new major version of the library at a later time. We can include that support then. But i can not say when.

**Comment by elysion** [comment]
Hi! I'd be glad to implement the support for the custom segments and create a pull request for you. What I had in mind was to add support in three phases:

1. Skip parsing of custom segments and print out a warning instead of throwing an error. With this change it would be possible to use the other parts of the message.
2. Parse the segments and create HL7Segment ignoring the schema / dictionary and setting the field name as "CustomFieldx" (as is done in HL7Segment.js:83) and using the string value as the field data.
3. Adding support for providing schema / dictionaries for custom segments.

The first step would probably be easy to implement. The second might be a bit more problematic at least if implemented cleanly. For the third one I am not really sure what would be the best way to implement it considering the current implementation.

Do you have opinions or ideas for the steps mentioned earlier? We would like to use this library for our current project, but some of the core functionality requires supporting custom segments.

**Comment by erayhanoglu** [comment]
If you ignoring the dictionary, you should never know the data type of the fields. So this will cause some problems setting data to fields. Instead of ignoring dictionary, adding support for defining additional dictionaries for user segments.
