### ISSUE TITLE
Wrong Message Control ID used in sendReceive?

### ISSUE THREAD

**Issue by balazs-ge** [panates/hl7v2#2]
This is a wonderful library, thanks for creating and supporting it.
I think in the HL7Client there might be a bug.

```
  _onMessage(msg) {
    const contId = msg.MSH.MessageControlId.value;
    if (this._waitQueue[contId]) {
      const fn = this._waitQueue[contId];
      delete this._waitQueue[contId];
      fn(msg);
      return;
    }
    this.emitSafe('message', msg);
  }
```

I think the _onMessage function should take the value for contId not from the MSH segment of the response, but from the MSA segment, where the Message Control ID of the original request is echoed. Thus, I think this line is incorrect:
`    const contId = msg.MSH.MessageControlId.value;
`

**Comment by balazs-ge** [comment]
Proposed fix:

```
  _onMessage(msg) {
    try {
      const contId = msg.getSegment('MSA').MessageControlId.value;
      if (this._waitQueue[contId]) {
        const fn = this._waitQueue[contId];
        delete this._waitQueue[contId];
        fn(msg);
        return;
      }
      this.emitSafe('message', msg);
    } catch (ignored) {
      // ignored
    }
  }
```

**Comment by erayhanoglu** [comment]
You are right! We ve fixed the issue. Thank you for your feedback.
