### ISSUE TITLE
Cannot find module '/dictionary/2.3.1'

### ISSUE THREAD

**Issue by bradsour** [panates/hl7v2#23]
`
const msg = new hl7v2.HL7Message()
msg.add('MSH')
`

The above statements are causing me to crash getting cannot find module '/dictionary/2.3.1'

I looked into my node_modules and see the dictionary folder is created. I'm unsure if I have just missed a setup step or if there is actually a bug here.

**Comment by bradsour** [comment]
`/* eslint-disable react/state-in-constructor */
/* eslint-disable import/no-unresolved */
/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable react/jsx-props-no-spreading */
import cal from '@iatric/fastlane-client-app-library';
import React, { Component } from 'react';
//import { Card, CardBody, CardHeader, Col, Row } from 'reactstrap';
import classes from './message.css';

const { HL7Message } = require('hl7v2')
const { ContentArea } = cal;

class Message extends Component {
  constructor(props) {
    super(props);
    this.state = {
      messenger: null,
      message: null,
      hl7: null
    };
    const msg = new HL7Message()
    console.log(msg)
    msg.add('MSH')
    console.log(msg)
    //const msg2 = HL7Message.parse('MSH|^~\\&|A^B^C^D')
    //console.log(msg2)
  }

  render() {
    return (
      <ContentArea header="Message 2">
        {/*<div>{this.state.hl7}</div>*/}
      </ContentArea>
    );
  }
}

export default Message;
`

I get results from the initial console.log after instantiating msg, but after that doing the msg.add('MSH') does not console log also my render doesn't get displayed. It does if I comment out the msg.add('MSH')

![image](https://user-images.githubusercontent.com/7378537/150600940-633444b3-053c-4099-a503-081989720b28.png)

**Comment by erayhanoglu** [comment]
Hi, the library is built to be use in NodeJS applications and didn't tested with any browser. The library loads dictionary files on the fly when it needs. You can use browserify to bundle whole library files into one file to use in browser.

**Comment by bradsour** [comment]
Thanks for the input.
