### ISSUE TITLE
Time fractions (ms) not decoded from Date/Time and Time

### ISSUE THREAD

**Issue by balazs-ge** [panates/hl7v2#3]
I've tested my HL7 implementation with IHE servers (Gazelle), where in the header I've got the following values:
MSH|^~\&|PatientManager|IHE|MyApp|MyFacility|20190521132215.844+0200||ACK^Q23^ACK|64321|P|2.5
This message could not be decoded due to the fraction in the Date/Time field, thus I got a timeout instead of being able to process the message.

I think the TS_PATTERN and TM_PATTERN regex are responsible for that in helpers.js.
Once fixed, the message could be handled as intended.

**Comment by erayhanoglu** [comment]
Hello. Added milliseconds and timezone parsing support. Please update your library to 0.8
