### ISSUE TITLE
Include an example server.js

### ISSUE THREAD

**Issue by bluepuma77** [panates/hl7v2#8]
A simple 10 line example `server.js` to receive messages and print them to console would help.

```
// not working!
const {HL7Message, HL7Server, HL7Client, createServer, connect} = require('hl7v2');
let server = new HL7Server();  
server.listen(7777).then(() => {
    console.log('Listening')
    server.use((req) => {
        console.log(req.toHL7());
    });
    server.use(() => ack);
});
```

I looked at the tests as recommend (#4) , but could not get it to work.

**Comment by erayhanoglu** [comment]
I've just checked. All test are passing. I think this line is the problem
```js
server.use(() => ack);
```
There is no function named "ack".

**Comment by bluepuma77** [comment]
Can the library build acknowledge messages to be sent back?

**Comment by bluepuma77** [comment]
I am looking for a NodeJS solution to 
1. Receive HL7v2 messages over TCP/IP
2. Parse the HL7 message
3. Print patient case number (and save fields to database)
4. If successful, send acknowledge message

**Comment by bluepuma77** [comment]
I am looking specifically for ADT messages:
A01 | Admit/visit notification
A02 | Transfer a patient
A03 | Discharge/end visit
A04 | Register a patient
A05 | Pre-admit a patient
A06 | Change an outpatient to an inpatient
A07 | Change an inpatient to an outpatient
A08 | Update patient information
A11 | Cancel admit/visit notification
A12 | Cancel transfer
A13 | Cancel discharge/end visit

**Comment by erayhanoglu** [comment]
The library receives HL7v2 messages over TCP/IP and parses the HL7 messages to JS classes. You can do anything you wand with HL7 objects in the async callback function. Server sends ack message when async function fulfills.

**Comment by bluepuma77** [comment]
It's nice that the library is open source, but the only documentation is `npm install hl7v2 --save`.

A bit of code to start your own server and receive HL7v2 messages:
```
const {HL7Message, HL7Server, HL7Client, createServer, connect} = require('hl7v2');

server = new HL7Server();
server.listen(8080).then(() => {
    console.log('Listening')
    server.use((msg) => {
        // print received HL7v2
        console.log(msg.toHL7().replace(/\r/g, "\r\n"));
        // print decoded structure
        console.log(JSON.stringify(msg, null, 4));
        // TODO: send ack
    });
});
```
